//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIprojectSerasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoComp
    {
        public int id { get; set; }
        public string nameComp { get; set; }
        public string cnpj { get; set; }
        public string address { get; set; }
        public int id_infoScore { get; set; }
    
        public virtual InfoScore InfoScore { get; set; }
    }
}
