//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIprojectSerasa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoScore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoScore()
        {
            this.infoComp = new HashSet<infoComp>();
        }
    
        public int id { get; set; }
        public int scoreComp { get; set; }
        public int launchNF { get; set; }
        public int openDebt { get; set; }
        public double valueDebt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoComp> infoComp { get; set; }
    }
}
